### ISSUE TITLE
Hardcoded calibration paths

### ISSUE THREAD

**Issue by Lecrapouille** [fadlio/kinect_ros2#2]
In lines: https://github.com/fadlio/kinect_ros2/blob/81f425b75d17b834939315ef64b3f7622012641f/src/kinect_ros2_component.cpp#L24

and: https://github.com/fadlio/kinect_ros2/blob/81f425b75d17b834939315ef64b3f7622012641f/src/kinect_ros2_component.cpp#L28

File paths are hardcoded. Could be nice to tell in the README to update them

**Comment by bribribriambriguy** [comment]
I will make pull request to fix
